SELECT SYS_CONTEXT ('USERENV', 'DB_NAME') as DATABASE, SYS_CONTEXT ('USERENV', 'SESSION_USER') as SESSION_USER, SYSDATE from dual;

SET SERVEROUTPUT ON;
SET TIMING ON;

-- Dropping the tables
 BEGIN
  	    EXECUTE IMMEDIATE	'DROP TABLE CUSTOMERS';
  EXCEPTION
  	 WHEN OTHERS
  	 THEN
  	    DBMS_OUTPUT.PUT_LINE('ERROR FOR '|| SQLCODE||'-'||SQLERRM );
  END;
  /
  
   BEGIN
  	    EXECUTE IMMEDIATE	'DROP TABLE ACCOUNTS';
  EXCEPTION
  	 WHEN OTHERS
  	 THEN
  	    DBMS_OUTPUT.PUT_LINE('ERROR FOR '|| SQLCODE||'-'||SQLERRM );
  END;
  /
  
   BEGIN
  	    EXECUTE IMMEDIATE	'DROP TABLE TRANSACTIONS';
  EXCEPTION
  	 WHEN OTHERS
  	 THEN
  	    DBMS_OUTPUT.PUT_LINE('ERROR FOR '|| SQLCODE||'-'||SQLERRM );
  END;
  /
 
 --Creating the tables, idexes and constraints
CREATE TABLE CUSTOMERS
(
	PERS_ID              INTEGER NOT NULL ,
	NM                   VARCHAR2(100 CHAR) NULL ,
	SUR_NM               VARCHAR2(100 CHAR) NULL ,
	ZIP                  INTEGER NULL ,
	CITY                 VARCHAR2(100 CHAR) NULL ,
	CNTRY                VARCHAR2(100 CHAR) NULL ,
	EMAIL                VARCHAR2(1000 CHAR) NULL ,
	PHN_NBR              VARCHAR2(50 CHAR) NULL ,
	DOB                  VARCHAR2(50 CHAR) NULL 
);

CREATE UNIQUE INDEX XPK_CUSTOMERS ON CUSTOMERS
(PERS_ID   ASC);

ALTER TABLE CUSTOMERS
	ADD CONSTRAINT  XPK_CUSTOMERS PRIMARY KEY (PERS_ID);


CREATE TABLE ACCOUNTS
(
	ACCT_ID              INTEGER NOT NULL ,
	PERS_ID              INTEGER NULL ,
	ACCT_TYP             VARCHAR2(50 CHAR) NULL 
);

CREATE UNIQUE INDEX XPK_ACCOUNTS ON ACCOUNTS
(ACCT_ID   ASC);

ALTER TABLE ACCOUNTS
	ADD CONSTRAINT  XPK_ACCOUNTS PRIMARY KEY (ACCT_ID);

CREATE  INDEX XFK_ACCOUNTS_CUSTOMERS ON ACCOUNTS
(PERS_ID   ASC);



CREATE TABLE TRANSACTIONS
(
	TRANS_ID             INTEGER NOT NULL ,
	ACCT_ID              INTEGER NOT NULL ,
	TRANS_TYP            VARCHAR2(50 CHAR) NULL ,
	TRANS_DT             DATE NULL ,
	TRANS_AMT            NUMBER(10,6) NULL 
);

CREATE UNIQUE INDEX XPK_TRANSACTIONS ON TRANSACTIONS
(TRANS_ID   ASC);

CREATE  INDEX XFK_TRANSACTIONS_ACCOUNTS ON TRANSACTIONS
(ACCT_ID   ASC);

CREATE  INDEX INDX_TRANS_DT ON TRANSACTIONS
(TRANS_DT   ASC);

ALTER TABLE TRANSACTIONS
	ADD CONSTRAINT  XPK_TRANSACTIONS PRIMARY KEY (TRANS_ID);


ALTER TABLE ACCOUNTS
	ADD (CONSTRAINT R_ACCOUNTS_CUSTOMERS FOREIGN KEY (PERS_ID) REFERENCES CUSTOMERS (PERS_ID) ON DELETE SET NULL);

ALTER TABLE TRANSACTIONS
	ADD (CONSTRAINT R_TRANSACTIONS_ACCOUNTS FOREIGN KEY (ACCT_ID) REFERENCES ACCOUNTS (ACCT_ID) ON DELETE SET NULL);
	
SPOOL OFF;


